### ISSUE TITLE
Weird unidentifable crashes

### ISSUE THREAD

**Issue by Ninetalerise** [yungnickyoung/YUNGs-Cave-Biomes#12] opened 2024-10-07 17:41 UTC
So I recently added Yung's Cave Biomes to my personal modpack and I started receiving random crashes. I tried looking at the crash report but cannot find any immediate culprits for incompatibility issues. But with my minimal knowledge in this subject, it seems like it may be a chunk generation issue with structures? I can confirm it's this mod as when I remove it and make a new world with the same seed for these two worlds then teleport to the affected structures, my game runs smoothly without issue. I also want to note that it's not a bugged structure as when I load a different world seed with the mod, the structure is fine sometimes. It's the pure randomness that's making it really hard for me to find the true cause of this issue because it doesn't always occur.

[https://mclo.gs/fpuYkse](https://mclo.gs/fpuYkse)
[https://mclo.gs/ytRc9HP](https://mclo.gs/ytRc9HP)

**Comment by qRazvan03** [comment] 2024-10-08 13:09
I have this exact same problem, I put YUNG'S Cave Biomes in my modpack and it suddenly starts to give me random crashes.

**Comment by 4kGoat** [comment] 2024-10-08 14:52
I fixed this by removing redirector https://www.curseforge.com/minecraft/mc-mods/redirector

**Comment by yungnickyoung** [comment] 2024-10-08 17:43
Going to close this as a duplicate of #4 . Will continue the conversation over there

**Closed as completed by yungnickyoung** 2024-10-08 17:43 UTC
Labels: duplicate
